### ISSUE TITLE
display link to pretix if cross domain js is disabled

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-conf-website#33]
i block cross domain js by default (umatrix extension), which results in
![image](https://github.com/matrix-org/matrix-conf-website/assets/2803622/4d543e57-320a-425d-924f-b03c6f31b252)

**Comment by thibaultamartin** [comment]
Interesting, the `noscript` tag doesn't work here? If [this doesn't do the trick](https://github.com/matrix-org/matrix-conf-website/blob/main/templates/register.html#L75-L81), I'm not sure how to fix it

**Comment by HarHarLinks** [comment]
i think was happens is
1. js is enabled, so noscript tag isnt hit
2. the request for the xsite js fails e.g. as if the site was down
3. there's nothing to handle this case

**Comment by thibaultamartin** [comment]
Alright that seems to be a fairly niche use case, that only uMatrix users will stumble upon. The uMatrix [has been archived in 2021](https://github.com/gorhill/uMatrix), and I'm fairly sure uMatrix users are used to websites breaking when they block content.

If there's a quick and simple solution, happy to merge it, but I don't think it's the best use of our time to spend too many cycles on this right now
